---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Create a new instance
      one_vm:
        api_url: "{{ molecule_yml.driver.options.api_url }}"
        api_username: "{{ molecule_yml.driver.options.api_username }}"
        api_password: "{{ molecule_yml.driver.options.api_password }}"
        template_name: "{{ item.name }}"
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      register: server

    # Mandatory configuration for Molecule to function.

    - when: server.changed | bool
      block:

        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'vm_id': "{{ item.instances[0].vm_id }}",
              'instance': "{{ item.instances[0].vm_name }}",
              'address': "{{ item.instances[0].networks[0].ip }}", }
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          copy:
            content: "{{ instance_conf | to_json | from_json | to_yaml }}"
            dest: "{{ molecule_instance_config }}"
            mode: 0600

        - name: Wait for instance(s) to be available
          wait_for:
            timeout: 60
