---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy instance
      one_vm:
        api_url: "{{ molecule_yml.driver.options.api_url }}"
        api_username: "{{ molecule_yml.driver.options.api_username }}"
        api_password: "{{ molecule_yml.driver.options.api_password }}"
        instance_ids:
          - "{{ hostvars[item].vm_id }}"
        state: absent
      with_items: "{{ hostvars }}"
      register: server

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config  # noqa 503
      copy:
        content: |
          # Molecule managed
          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: 0600
      when: server.changed | bool
